# This is a basic workflow to help you get started with Actions

name: PRODUCTION CD

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      # Runs a set of commands using the runners shell
      - name: Deploy to ec2
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            # Now we have got the access of EC2 and we will start the deploy.

            # Use a login shell to ensure all environment variables (like nvm, node, pm2) are correctly loaded
            source ~/.bashrc

            # Navigate to the app directory
            cd apps/coding-cms-nextjs
            
            # Update the codebase
            git switch master
            git fetch origin master
            git pull origin master

            # Install dependencies and build
            pnpm install --frozen-lockfile
            pnpm run build

            # Check if PM2 knows about our app
            if pm2 show coding-cms-nextjs > /dev/null 2>&1; then
              echo "Application is registered in PM2, restarting..."
              pm2 restart coding-cms-nextjs
            else 
              echo "Application is not registered in PM2, starting..."
              pm2 start pnpm --name "coding-cms-nextjs" -- run start
            fi
          '
